
server:
  port: 9999

spring:
  redis:
    port: 6380
    password: 123456
    host: 47.115.42.52
    database: 0

  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
